using Treasara.Api.Extensions;

// ============================================================================
// Treasara API Application Entry Point
// ============================================================================
//
// This is the main entry point for the Treasara fixed-income valuation API.
// The application uses a minimal hosting model with extension methods to
// organize configuration into logical groups.
//
// Architecture:
// - ConfigureTreasaraLogging: Sets up structured logging with Serilog
// - AddTreasaraApi: Registers all services (controllers, validators, mappers, etc.)
// - UseTreasaraApiPipeline: Configures middleware pipeline (CORS, auth, logging, etc.)
// - MapTreasaraEndpoints: Maps controllers and health check endpoints
//
// See the Extensions folder for detailed configuration of each component.
// ============================================================================

var builder = WebApplication.CreateBuilder(args);

// Configure structured logging with Serilog
// See: WebApplicationBuilderExtensions.cs for logging configuration details
builder.ConfigureTreasaraLogging();

// Register application services (DI container configuration)
// Includes: Controllers, validators, mappers, AutoMapper, FluentValidation, etc.
// See: ServiceCollectionExtensions.cs for service registration details
builder.Services.AddTreasaraApi(builder.Configuration);

// Build the application
var app = builder.Build();

// Configure the HTTP request pipeline (middleware)
// Includes: Exception handling, CORS, authentication, authorization, rate limiting, etc.
// See: WebApplicationExtensions.cs for middleware pipeline configuration
app.UseTreasaraApiPipeline();

// Map API endpoints and health checks
// Configures routing for controllers and health check endpoints
// See: WebApplicationExtensions.cs for endpoint mapping details
app.MapTreasaraEndpoints();

// Start the application and begin listening for requests
app.Run();

/// <summary>
/// Partial class declaration for the Program type, used for integration testing.
/// </summary>
/// <remarks>
/// This partial class declaration makes the Program type accessible to test projects,
/// enabling WebApplicationFactory-based integration tests. Without this declaration,
/// the implicit Program class generated by top-level statements would be internal
/// and inaccessible to test assemblies.
/// 
/// WebApplicationFactory uses this to bootstrap the application in-memory for testing:
/// <code>
/// public class MyTests : IClassFixture&lt;WebApplicationFactory&lt;Program&gt;&gt;
/// {
///     // Tests can create HttpClient instances and make requests
/// }
/// </code>
/// 
/// The partial keyword allows this declaration to be combined with the compiler-generated
/// Program class, maintaining the clean top-level statements syntax while enabling testability.
/// 
/// See: <see href="https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests">ASP.NET Core Integration Tests</see>
/// </remarks>
public partial class Program
{
}